### ISSUE TITLE
Question: Any way to control wsdltophp/packagebase version in outpuit composer.json?

### ISSUE THREAD

**Issue by BorislavSabev** [WsdlToPhp/PackageGenerator#104]
Hello.
My questions is as simple as that:
Is there any way to control wsdltophp/packagebase version in outpuit composer.json?
Currently it outputs "dev-master" whilst at the same time you do have tagged releases.

BTW: Excellent idea with this package generator. It rocks for implementing 3rd party SOAP web services!

**Comment by mikaelcom** [comment]
Which PackageGenerator version are you using? The `wsdltophp/packagebase` version is fixed in the [Composer file](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/File/Composer.php#L34) generator with version ~1.0 since a while, Currently, you don't have the possibility to set it on generation but as it does not evolve a lot, ~1.0 should suffice.

BTW: thx. If you like it, star it :wink:

**Comment by BorislavSabev** [comment]
I have cloned your `wsdltophp/packagegenerator` repo locally and am using it to build various packages. Even if I update to the latest versions via composer:

````
Updating wsdltophp/phpgenerator dev-master (837760a => 03494f3):  Checking out 03494f3bc3
Updating wsdltophp/packagebase dev-master (be17fa3 => 4829b0e):  Checking out 4829b0ee4a
````

I still get ` "wsdltophp/packagebase": "dev-master"` in the target. I am generating in "standalone mode".

Maybe this is because I am using dev-master to generate.

**Comment by mikaelcom** [comment]
If I do this:
```bash
$ cd /tmp
$ git clone https://github.com/WsdlToPhp/PackageGenerator.git
$ cd PackageGenerator
$ git checkout master
$ composer install
$ ./console g:p --urlorpath="./tests/resources/bingsearch.wsdl" \
                --destination="/tmp/Bing" \
                --composer-name="bing/search" \
                --force
```

I get this generated composer.json file:
```json
{
    "name": "bing/search",
    "description": "Package generated from ./tests/resources/bingsearch.wsdl using wsdltophp/packagegenerator",
    "require": {
        "php": ">=5.3.3",
        "ext-soap": "*",
        "wsdltophp/packagebase": "~1.0"
    },
    "autoload": {
        "psr-4": {
            "": "./src/"
        }
    }
}
```

Is it what you're doing?

**Comment by BorislavSabev** [comment]
Hello.

No I am using the PHP OOP utilities to generate:

```
$opt = GeneratorOptions::instance();
$addComments = [
    'date' => date('Y-m-d'),
    'author' => 'Borislav Sabev <bsabev@example.com>',
    'release' => '1.1',
];

$opt->setOrigin('__WSDL_URL__')
    ->setDestination($destination)
    ->setComposerName("borkata/{$packageName}")
    ->setNamespace("borkata\\{$packageName}")
    ->setAddComments($addComments);

$generator = new Generator($opt);
$generator->generatePackage();
```

I tested it with the console executable in my current installation path and it is the same output.
I tested in a new git clone and **it is correct**. So I guess there is something leaking from the composer settings in my original PATH.

Thanks for the support. I will rebuild my environment
